/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package de.vp;

import java.io.File;
import java.nio.file.Path;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;

/**
 *
 * @author Maxi
 */
public class Start extends javax.swing.JFrame {

    /**
     * Creates new form Start
     */
    public Start() {
        initComponents();
        ImageIcon icon = new ImageIcon(getClass().getResource("images/icon.png"));
        setIconImage(icon.getImage());
        getRootPane().setDefaultButton(spielStartenButton); // Wenn man jetzt Enter drückt gelangt man in den Prolog
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spielStartenButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        hoeheComboBox = new javax.swing.JComboBox();
        breiteComboBox = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        creditsButton = new javax.swing.JButton();
        spielLadenButton = new javax.swing.JButton();
        hintergrund = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Verkehrsplaner");
        setMinimumSize(new java.awt.Dimension(577, 275));
        setResizable(false);
        getContentPane().setLayout(null);

        spielStartenButton.setText("Spiel Starten");
        spielStartenButton.setToolTipText("Startet das Spiel!");
        spielStartenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spielStartenButtonActionPerformed(evt);
            }
        });
        getContentPane().add(spielStartenButton);
        spielStartenButton.setBounds(160, 170, 110, 23);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Höhe:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(160, 147, 50, 14);

        hoeheComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "50", "100", "500", "1000" }));
        hoeheComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hoeheComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(hoeheComboBox);
        hoeheComboBox.setBounds(210, 140, 60, 20);

        breiteComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "50", "100", "500", "1000" }));
        getContentPane().add(breiteComboBox);
        breiteComboBox.setBounds(330, 140, 60, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Breite:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(280, 147, 50, 14);

        creditsButton.setText("Credits");
        creditsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditsButtonActionPerformed(evt);
            }
        });
        getContentPane().add(creditsButton);
        creditsButton.setBounds(445, 220, 90, 23);

        spielLadenButton.setText("Spiel laden");
        spielLadenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spielLadenButtonActionPerformed(evt);
            }
        });
        getContentPane().add(spielLadenButton);
        spielLadenButton.setBounds(280, 170, 110, 23);

        hintergrund.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/vp/images/start.png"))); // NOI18N
        hintergrund.setToolTipText("");
        getContentPane().add(hintergrund);
        hintergrund.setBounds(0, 0, 577, 270);

        setSize(new java.awt.Dimension(567, 295));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Durch einen File-Chooser kann ein Spielstand geladen werden
     * 
     * @param evt 
     */
    private void spielLadenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spielLadenButtonActionPerformed
        JFileChooser fc = new JFileChooser();
        fc.removeChoosableFileFilter(fc.getAcceptAllFileFilter());
        fc.setFileFilter(new FileFilter() {

            @Override
            public boolean accept(File file) {
                if (file.isDirectory()) {
                    return true;
                }
                return file.getName().toLowerCase().endsWith(".vp");
            }
            public String getDescription() {
                return "Spielstände";
            }
            
        });
        int returnVal = fc.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            Path file = fc.getSelectedFile().toPath();
            Sound sound = new Sound();
            sound.musikAn();
            JFrame f = new SpielGUI(file, sound);
            f.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_spielLadenButtonActionPerformed

    /**
     * Eine neue GUI 'Credits' wird geöffnet
     * 
     * @param evt 
     */
    private void creditsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditsButtonActionPerformed
        JFrame f = new CreditsGUI();
        f.setVisible(true);
    }//GEN-LAST:event_creditsButtonActionPerformed

    /**
     * Es wird die Mindestgröße des Feldes überprüft
     * Eine neue GUI 'Prolog' erscheint
     * 
     * @param evt 
     */
    private void spielStartenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spielStartenButtonActionPerformed
        int hoehe = Integer.parseInt((String) hoeheComboBox.getModel().getElementAt(hoeheComboBox.getSelectedIndex())); //Setzt hoehe = ComboBox
        int breite = Integer.parseInt((String) breiteComboBox.getModel().getElementAt(breiteComboBox.getSelectedIndex()));
        try {
            if (hoehe < 50 && breite < 50) {
//                System.out.println("Zahl kleiner als 50!");
                JOptionPane.showMessageDialog(null, "Das Spielfeld muss mindestens 50x50 groß sein!", "Fehler", JOptionPane.ERROR_MESSAGE);
            } else {
                JFrame f = new PrologGUI(hoehe, breite);
                f.setVisible(true);
                dispose();
            }
        } catch (NumberFormatException ex) {
//            System.out.println("Keine Zahl!");
            JOptionPane.showMessageDialog(null, "Bitte eine gültige Zahl eingeben!", "Fehler", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_spielStartenButtonActionPerformed

    private void hoeheComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hoeheComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hoeheComboBoxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox breiteComboBox;
    private javax.swing.JButton creditsButton;
    private javax.swing.JLabel hintergrund;
    private javax.swing.JComboBox hoeheComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton spielLadenButton;
    private javax.swing.JButton spielStartenButton;
    // End of variables declaration//GEN-END:variables
}
